name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - '../backend/**'
      - '.github/workflows/appservice.yml'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Backend
    # App Service Publish Profile が設定されている場合のみ実行
    if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exitai-backend'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './backend'
          startup-command: 'gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000'
